### ISSUE TITLE
Does ::theme really exist?

### ISSUE THREAD

**Issue by manueledones** [fergald/docs#4]
Hi fergald,

sorry to bother you, I was reading the doc css-shadow-parts-1.md and I'm trying to figure out how to make ::theme works.

I'm trying to use it but my latest Chrome doesn't recognize as a valid pseudoselector.
I cannot find it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements)
or [here](https://caniuse.com/#search=%3A%3Atheme)

So I start thinking it's not available yet, or it has been canceled ?

Any news about that?

Thank you

**Comment by fergald** [comment]
Theme was cut from the [spec](https://www.w3.org/TR/css-shadow-parts-1/) because there was no agreement on it and part was pretty well agreed. So part shipped in Chrome and I think Safari and Mozilla. I not longer work in this area, so I won't be pushing theme. I don't know if anyone else is.

Theme's problem is that it seems like component authors and component users would want ways to limit application of theme. Do we do that with allow-lists? Disallow-lists? Both? How do you express it, how do you propagate that info into or out of subcomponents. Maybe the answer is to just ship without any of that and see if that works.

At all points in the standards process, we need to know that we're solving real user needs, so if you have a need, it would be great to express that somewhere (here is fine, I can CC some revelant people if you do). Use case, what corner cases do you need for real etc.

**Comment by manueledones** [comment]
Thank you for your reply, I don't have any real use case, I was just playing with web components, I read about that ::theme pseudo-element and didn't find any reference it has been dropped from the spec.
For example a link to your doc can be found in the [developer.mozilla.org web site](https://developer.mozilla.org/en-US/docs/Web/CSS/::part), but there's no indication that ::theme is "gone".

Thank you for the explanation, cheers! :)

**Comment by fergald** [comment]
Explainers don't describe what has been built, in general they explain what someone envisions, that gets turned into a spec people agree on and then that gets built. There is currently no spec for theme. The spec for part is above (and also linked from MDN). The spec for part used to include stuff about theme but it was not very far along.
